name: Deploy

on:
  push:
    branches: ["main"]

  # Deploy on a schedule to ensure card data is up to date.
  schedule:
    - cron: 0 3 * * *

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

# TODO: Make it work with Kotlin/Gradle.
