name: Update Cards

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "update-cards"
  cancel-in-progress: false

jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache SF bulk dumps
        uses: actions/cache@v4
        with:
          path: preprocessing
          key: ${{ runner.os }}-preprocessing

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Bun install
        run: bun install --production --frozen-lockfile

      - name: Bun preprocess
        run: bun preprocess

      - name: Commit and Push
        run: |
          git config --global user.name 'Daan Vanden Bosch'
          git config --global user.email 'daan.v.d.bosch@gmail.com'
          
          if [ -n "$(git status --porcelain)" ]
          then
            git commit -am "Card update."
            git push
          else
            echo 'No changes'.
          fi
